### ISSUE TITLE
Missing detailed environment configuration and some necessary running modules

### ISSUE THREAD

**Issue by huzimun** [riolys/DisDiff#1]
Dear authors, I meet the following problems:
1. train_dreambooth.py used in disdiff.sh is lacked.
2. Line 32 of disdiff.py, "from show_attention import Attmap" causes an error "ModuleNotFoundError: No module named 'show_attention", I cannot find this module from your codes.
I also suggest you provide detailed environment configuration in this repository, such as a requirements.txt.

**Comment by riolys** [comment]
Refer to README.md plz, we use the environment and other python files of Anti-db. By the way, if you thought the versions of packages are old,  our code can be reproduced by the lastest version of diffusers and transformers,  just use "pip install" to download what you need.
